[package]
name = "ic-btc-consensus"
version = "0.1.0"
edition = "2018"

[dependencies]
ic-btc-types-internal = { path = "../types/internal" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-bitcoin-adapter-client = { path = "../../interfaces/bitcoin_adapter_client" }
ic-interfaces-state-manager = { path = "../../interfaces/state_manager" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-replicated-state = { path = "../../replicated_state" }
ic-registry-subnet-features = { path = "../../registry/subnet_features" }
ic-types = { path = "../../types/types" }
prometheus = { version = "0.12.0", features = [ "process" ] }
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
thiserror = "1.0"

[dev-dependencies]
ic-protobuf = { path = "../../protobuf" }
ic-test-utilities = { path = "../../test_utilities" }
